### ISSUE TITLE
Clients map gets empty

### ISSUE THREAD

**Issue by kettanaito** [mswjs/msw#105]
## Describe the bug
After some interval, or unexpected event, the internal map of `clients` controlled by the worker becomes empty.

## Environment

- `msw: 0.13.0`
- `nodejs: 10.16.3`
- `npm: 6.9.0`

> Please also provide your browser version.

Chrome Version 81.0.4044.113 

### Mocks

```js
import { composeMocks, rest } from 'msw'

const { start } = composeMocks(
  rest.get('https://api.github.com/users/:username', (req, res, ctx) => {
    const { username } = req.params

    return res(
      ctx.status(200),
      ctx.json({
        avatar_url: '/avatar.png',
        login: username,
        name: 'John Maverick',
        bio: 'This is a mocked bio.',
      }),
    )
  }),
)

start()
```

### Client

```jsx
import React, { useState, useCallback } from 'react'
import { Card, Input, Avatar } from 'antd'

export const App = () => {
  const [data, setData] = useState(null)
  const [isLoading, setLoading] = useState(false)

  const handleSearch = useCallback((username) => {
    if (!username) {
      return
    }

    setData(null)
    setLoading(true)

    fetch(`https://api.github.com/users/${username}`)
      .then((res) => res.json())
      .then(setData)
      .then(() => setLoading(false))
      .catch(() => setLoading(false))
  }, [])

  return (
    <main>
      <Card title="GitHub User Preview" style={{ width: '100%' }}>
        <Input.Search
          size="large"
          name="username"
          placeholder="Enter GitHub username"
          enterButton="Preview"
          autoComplete="off"
          spellCheck={false}
          loading={isLoading}
          onSearch={handleSearch}
        />
      </Card>
      {data && (
        <Card.Meta
          title={`${data.name} (${data.login})`}
          avatar={<Avatar src={data.avatar_url} size={60} alt={data.name} />}
          description={data.bio}
          style={{ margin: '32px 24px' }}
        />
      )}
    </main>
  )
}
```

## Expected behavior
The `clients` map never becomes empty if there's an existing client (tab).

## Screenshots

Here's a logging of the intercepted request that goes unexpected:

<img width="1501" alt="Screen Shot 2020-04-19 at 14 00 47" src="https://user-images.githubusercontent.com/14984911/79687252-41b62880-8246-11ea-8f03-33ef78676bbe.png">

As you can see, the `clients` map (second) is an empty object, while I'm working with a tab that has the worker registered.

**Comment by kettanaito** [comment]
Perhaps a coincidence, but I've encountered this error when I was able to reproduce this issue:

```
mockServiceWorker.js:163 [MSW] Failed to mock a "GET" request to "http://localhost:3000/": TypeError: Failed to execute 'fetch' on 'WorkerGlobalScope': 'only-if-cached' can be set only with 'same-origin' mode
    at getOriginalResponse (http://localhost:3000/mockServiceWorker.js:71:37)
    at http://localhost:3000/mockServiceWorker.js:85:24
```

> Issue raised regarding this: #107
