### ISSUE TITLE
MSW seems not to work with kafka testcontainers

### ISSUE THREAD

**Issue by ofekdeitch-oligo** [mswjs/msw#1600]
### Prerequisites

- [X] I confirm my issue is not in the [opened issues](https://github.com/mswjs/msw/issues)
- [X] I confirm the [Frequently Asked Questions](https://mswjs.io/docs/faq) didn't contain the answer to my issue

### Environment check

- [X] I'm using the [latest](https://github.com/mswjs/msw/releases/latest) `msw` version
- [X] I'm using Node.js version 14 or higher

### Node.js version

18.16.0

### Reproduction repository

https://github.com/ofekdeitch-oligo/msw-testcontainers-bug

### Reproduction steps

run:
1. `nvm use`
2. `npm install`
3. `npm run test`

Notice that there are 2 tests running:
1. Without MSW
2. With MSW

Test (1) passes, but test (2) fails.

I've also added the method `bypassRoutes` that creates routes using `req.passthrough()`, but test (2) continues to fail.

### Current behavior

When setting up an MSW server, the `testcontainers` library fails to create a Kafka container.

### Expected behavior

MSW would bypass the requests that testcontainers relies on, so that a Kafka container would be created successfully.

**Comment by kettanaito** [comment]
Hi, @ofekdeitch-oligo. Thanks for reporting this.

From my experience, issues like these are often related to how the third-party agent (in your case the `testcontainers` package) constructs and performs the request. I can't count the number of times libraries go into strange tropes, sometimes even against the Node.js API, and then issues surface through libraries like MSW, which let you execute _more_ of the request code. 

I don't have the time capacity to look into this, so anybody is welcome to debug the issue and share their findings. Thank you for understanding.

**Comment by vinialbano** [comment]
I'm not sure if it's the same issue, but MSW somehow is preventing Ryuk from finish.
I'm using TestContainers with PostgreSQL. My test passes, the PG container is shut down, but Jest never closes and Ryuk is never shut down.
There's probably something messing with the HTTP communication with Docker. Maybe it's related to this Event Emitter warning? @kettanaito 
<img width="1350" alt="Image" src="https://github.com/user-attachments/assets/e562fe14-e036-4235-b6af-2150434770a5" />

**Comment by satanshiro** [comment]
@vinialbano I can confirm that I have similar problem test container was continually failing with
`Could not find a working container runtime strategy`
looking at your issue at nock i was able to solve it by overriding mswjs interceptor package via

```
    "msw": {
      "@mswjs/interceptors": "0.37.5"
    }
```

in fact using another version did not work for me

**Comment by kettanaito** [comment]
@satanshiro, does that mean a _newer_ version of Interceptors helps?

**Comment by satanshiro** [comment]
@kettanaito I meant to say when I tried using a different version other than the one i noted above (0.37.5) I was unsuccessful, there is a newer version of interceptors which resulted in same error

**Comment by serhat-m** [comment]
Hi, I'm encountering a similar error with `msw` and `@testcontainers/postgresql` under Vitest. Unhandled request strategy is set to `bypass`. Override with `@mswjs/interceptors: 0.37.5` works like a charm, thank you @satanshiro.

### PG TestContainer Error:

```
{
  stack: 'AggregateError: \n' +
    '    at internalConnectMultiple (node:net:1139:18)\n' +
    '    at afterConnectMultiple (node:net:1714:7)',
  errors: [
    {
      stack: 'Error: connect ECONNREFUSED ::1:80\n' +
        '    at createConnectionError (node:net:1677:14)\n' +
        '    at afterConnectMultiple (node:net:1707:16)',
      message: 'connect ECONNREFUSED ::1:80',
      errno: -61,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '::1',
      port: 80,
      constructor: 'Function<Error>',
      name: 'Error',
      toString: 'Function<toString>'
    },
    {
      stack: 'Error: connect ECONNREFUSED 127.0.0.1:80\n' +
        '    at createConnectionError (node:net:1677:14)\n' +
        '    at afterConnectMultiple (node:net:1707:16)',
      message: 'connect ECONNREFUSED 127.0.0.1:80',
      errno: -61,
      code: 'ECONNREFUSED',
      syscall: 'connect',
      address: '127.0.0.1',
      port: 80,
      constructor: 'Function<Error>',
      name: 'Error',
      toString: 'Function<toString>'
    }
  ],
  code: 'ECONNREFUSED',
  stackStr: 'AggregateError: \n' +
    '    at internalConnectMultiple (node:net:1139:18)\n' +
    '    at afterConnectMultiple (node:net:1714:7)',
  nameStr: 'AggregateError',
  expected: 'undefined',
  actual: 'undefined',
  message: '',
  constructor: 'Function<AggregateError>',
  name: 'AggregateError',
  toString: 'Function<toString>',
  stacks: []
}
```

**Comment by jczstudios** [comment]
This was driving me nuts this afternoon, trying to figure out what was causing my tests to timeout...

**Comment by vinialbano** [comment]
@kettanaito I created a pull request to fix this issue. TestContainers rely on UNIX sockets, and the interceptors library didn't handle them. I was able to debug, confirm, and propose a solution.

Here's a [Gist with tests](https://gist.github.com/vinialbano/4950006ee836c66cf27d87810e35022c) for the MSW integration with TestContainers. They work properly after my fix is introduced.

@msutkowski @marcosvega91 @timdeschryver

**Comment by sbitproz** [comment]
I'm not sure if this issue is related, but I'm using AWS localstack with testcontainers.  In localstack, I'm running Kafka and AWS Glue.  The service we're building communicates with AWS Glue through REST. 

When using msw@2.7.3 the requests appear to reach the test container and testing runs as expected.

When using msw@2.11.3 the request appears to fail; perhaps the request is intercepted for whatever reason.  I've stripped back my handlers to be an empty array to rule out any wildcard issues.  The error message I see with 2.11.3 is as follows:

```
error: TypeError: Cannot create property 'message' on string 'm'
    Deserialization error: to see the raw response, inspect the hidden field {error}.$response on this object.
      at parseJsonErrorBody (/Users/dan/projects/service/node_modules/@aws-sdk/core/dist-cjs/submodules/protocols/index.js:362:17)
      at processTicksAndRejections (node:internal/process/task_queues:95:5)
      at runNextTicks (node:internal/process/task_queues:64:3)
      at processTimers (node:internal/timers:511:9)
      at de_CommandError (/Users/dan/projects/service/node_modules/@aws-sdk/client-glue/dist-cjs/index.js:7696:11)
      at /Users/dan/projects/service/node_modules/@smithy/middleware-serde/dist-cjs/index.js:36:20
      at /Users/dan/projects/service/node_modules/@smithy/core/dist-cjs/index.js:193:18
      at /Users/dan/projects/service/node_modules/@smithy/middleware-retry/dist-cjs/index.js:312:38
      at /Users/dan/projects/service/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:33:22
      at PromiseDispatcher.run (/Users/dan/projects/service/node_modules/@meinestadt.de/glue-schema-registry/src/index.ts:83:14)
      at GlueSchemaRegistry.createSchema (/Users/dan/projects/service/node_modules/@meinestadt.de/glue-schema-registry/src/index.ts:157:17)
      at GlueAdminService.createSchema (/Users/dan/projects/service/src/glue/services/glue.admin.service.ts:32:22) {
    '$metadata': [Object]
  },
  [Symbol(level)]: 'error',
  [Symbol(splat)]: [ [Object] ],
  [Symbol(message)]: '{"error":{"$metadata":{"attempts":3,"httpStatusCode":500,"totalRetryDelay":160}},"level":"error","message":"Error creating schema","schemaName":"some-schema","schemaPath":"/Users/dan/projects/service/src/glue/schemas/some.avsc","timestamp":"2025-09-22T10:44:02.022Z"}
```

with no handlers:

```
const setupHandler = () => {
 const handlers = [
  // commented handlers
  ];

  return setupServer(...handlers);
}
```

I've tried to use the bypass - but only had the same outcome.
```
server.listen({ onUnhandledRequest: 'bypass' });
```

Using the debug flag didn't surface anything either:
```
process.env.DEBUG='msw:*';
```
 
Does this sound like it could be related?  Do you have any suggestions?

**Comment by kettanaito** [comment]
Can someone please verify the _original_ issue is fixed? I believe we've merged the Unix path handling in Interceptors some time ago. Thanks.

**Comment by kettanaito** [comment]
Closing since no new verification arrived. Considering this closed.
