### ISSUE TITLE
setupServer: ReferenceError: location is not defined

### ISSUE THREAD

**Issue by kettanaito** [mswjs/msw#193]
## Describe the bug
When using `setupServer` I get the following exception sometimes:

```
(node:4754) UnhandledPromiseRejectionWarning: ReferenceError: location is not defined
    at resolveRelativeUrl (/Users/kettanaito/Projects/contrib/next.js/examples/with-msw/node_modules/msw/lib/umd/index.js:2614:16)
    at Object.predicate (/Users/kettanaito/Projects/contrib/next.js/examples/with-msw/node_modules/msw/lib/umd/index.js:2682:42)
    at handlers.reduce (/Users/kettanaito/Projects/contrib/next.js/examples/with-msw/node_modules/msw/node/index.js:476:28)
    at Array.reduce (<anonymous>)
    at /Users/kettanaito/Projects/contrib/next.js/examples/with-msw/node_modules/msw/node/index.js:464:55
    at Generator.next (<anonymous>)
    at /Users/kettanaito/Projects/contrib/next.js/examples/with-msw/node_modules/msw/node/index.js:28:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/kettanaito/Projects/contrib/next.js/examples/with-msw/node_modules/msw/node/index.js:24:12)
    at getResponse (/Users/kettanaito/Projects/contrib/next.js/examples/with-msw/node_modules/msw/node/index.js:463:40)
    at Object.<anonymous> (/Users/kettanaito/Projects/contrib/next.js/examples/with-msw/node_modules/msw/node/index.js:585:44)
    at Generator.next (<anonymous>)
    at /Users/kettanaito/Projects/contrib/next.js/examples/with-msw/node_modules/msw/node/index.js:28:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/kettanaito/Projects/contrib/next.js/examples/with-msw/node_modules/msw/node/index.js:24:12)
    at interceptor.use (/Users/kettanaito/Projects/contrib/next.js/examples/with-msw/node_modules/msw/node/index.js:565:38)
```

## Environment

- `msw: 0.18.0`
- `nodejs: v10.16.3`
- `npm: 6.x`

> Please also provide your browser version.

## To Reproduce

1. Setup a set of requests handlers that have a relative request URL.
1. Perform a request to an absolute URL.

While looking up the relevant request handler, MSW will stumble upon `/relative`, and would try to resolve it to the absolute, using `location.origin`.

## Expected behavior
Server-side code, or any code that can be used on server-side, does not rely on client-side global objects (i.e. `window`,` location`, etc.).

**Comment by ismoil793** [comment]
There is a solution at Stackoverflow please check out the link below:
https://stackoverflow.com/questions/65819812/location-is-not-defined-error-in-react-next-js/67670615#67670615

**Comment by kettanaito** [comment]
Hey, @ismoil793. Thanks for the reference. I believe this was an internal issue caused by relying on the `location` object that's not present in all environments where MSW can run.
