### ISSUE TITLE
Using msw with supertest in GraphQL testing is failing w/ 500 errors

### ISSUE THREAD

**Issue by bopfer** [mswjs/msw#286]
Note: This issue was spun off from my comments here: https://github.com/mswjs/msw/issues/209#issuecomment-653896198

In my GraphQL testing, I am trying to use `msw` to mock 3rd party REST calls, via GET.  But, I want my GraphQL app calls, via POST, to _not_ be intercepted/mocked.

But, when I  use `msw` and `supertest` at the same time in GraphQL testing, I get the following error:

```
 Received: [Error: cannot undefined undefined (500)]

  console.log
    Error: cannot undefined undefined (500)
        at Response.toError (node_modules/superagent/lib/node/response.js:94:15)
        at ResponseBase._setStatusProperties (node_modules/superagent/lib/response-base.js:123:16)
        at new Response (node_modules/superagent/lib/node/response.js:41:8)
        at Test.Request._emitResponse (node_modules/superagent/lib/node/index.js:752:20)
        at IncomingMessage.<anonymous> (node_modules/superagent/lib/node/index.js:916:38)
        at IncomingMessage.emit (events.js:326:22)
        at endReadableNT (_stream_readable.js:1226:12)
        at processTicksAndRejections (internal/process/task_queues.js:80:21) {
      status: 500,
      text: 'POST body missing. Did you forget use body-parser middleware?',
      method: undefined,
      path: undefined
    }
```

## Environment

- `msw: 0.19.5`
- `nodejs: 14.5.0`
- `yarn: 1.22.4`

## To Reproduce

See the README in this reproduction repo: https://github.com/bopfer/msw-supertest-issues

**Comment by kettanaito** [comment]
Hey, @bopfer. Thanks for reporting this.

I believe this issue has been tackled in https://github.com/mswjs/msw/issues/275 and solved. Expect the fix to be release in `msw@0.20.0` ([follow the progress](https://github.com/mswjs/msw/milestone/4)).

## Trying fix locally

You can also try it locally by:

```bash
# This clones and builds the latest "master" of MSW
$ git clone https://github.com/mswjs/msw
$ cd msw
$ yarn install
$ yarn build
$ yarn link
```

Then in your project:

```bash
# This links the locally built MSW in your project
$ yarn link msw
```

You need to verify that the version of `node-request-interceptor` package is `0.3.3`:

```bash
$ npm ls node-request-interceptor
```
