### ISSUE TITLE
Node - mocked Axios calls no longer work

### ISSUE THREAD

**Issue by andreawyss** [mswjs/msw#295]
This test project used to work https://github.com/andreawyss/msw-tester

Now 'npm test' fails for Axios.

node v12.16.3

Log details:
```
 PASS  src/procs/items-fetch.test.ts
 FAIL  src/procs/items-axios.test.ts
  ● Console

    console.log src/procs/items-axios.ts:10
      {
        data: '',
        status: 404,
        statusText: 'Not Found',
        headers: { 'x-powered-by': 'msw' },
        config: {
          url: '/items',
          headers: { Accept: 'application/json, text/plain, */*' },
          transformRequest: [ [Function: transformRequest] ],
          transformResponse: [ [Function: transformResponse] ],
          timeout: 0,
          adapter: [Function: xhrAdapter],
          xsrfCookieName: 'XSRF-TOKEN',
          xsrfHeaderName: 'X-XSRF-TOKEN',
          maxContentLength: -1,
          validateStatus: [Function: validateStatus],
          method: 'get',
          data: undefined
        },
        request: XMLHttpRequestOverride {
          requestHeaders: { Accept: 'application/json, text/plain, */*' },
          responseHeaders: { 'x-powered-by': 'msw' },
          _events: [],
          UNSENT: 0,
          OPENED: 1,
          HEADERS_RECEIVED: 2,
          LOADING: 3,
          DONE: 4,
          onreadystatechange: [Function: handleLoad],
          onabort: [Function: handleAbort],
          onerror: [Function: handleError],
          onload: null,
          onloadend: null,
          onloadstart: null,
          onprogress: null,
          ontimeout: [Function: handleTimeout],
          url: '/items',
          method: 'GET',
          readyState: 4,
          withCredentials: false,
          status: 404,
          statusText: 'Not Found',
          user: '',
          password: '',
          data: '',
          async: true,
          response: '',
          responseType: 'text',
          responseText: '',
          responseXML: null,
          responseURL: '',
          upload: null,
          timeout: 0
        }
      }

  ● getItemsWithAxios › handles server error

    expect(received).rejects.toThrowError(expected)

    Expected substring: "Request failed with status code 404"
    Received message:   "404: Not Found"

           9 |       const { response } = reason;
          10 |       console.log(response);
        > 11 |       throw new Error(`${response.status}: ${response.statusText}`);
             |             ^
          12 |     });
          13 | }
          14 | 

          at src/procs/items-axios.ts:11:13
          at Object.<anonymous> (src/procs/items-axios.test.ts:27:5)

      25 |   it('handles server error', async () => {
      26 |     server.use(...itemsMocks({ failOptions }));
    > 27 |     await expect(getItemsWithAxios()).rejects.toThrowError(
         |                                               ^
      28 |       `Request failed with status code ${failOptions.failCode}`
      29 |     );
      30 | 

      at Object.toThrowError (node_modules/expect/build/index.js:242:20)
      at Object.<anonymous> (src/procs/items-axios.test.ts:27:47)

  ● deleteWithAxios › handles server error

    expect(received).toBe(expected) // Object.is equality

    Expected: undefined
    Received: "Not Found"

      52 |     } catch (err) {
      53 |       expect(err.response.status).toBe(failOptions.failCode);
    > 54 |       expect(err.response.statusText).toBe(failOptions.failText);
         |                                       ^
      55 |     }
      56 |   });
      57 | });

      at Object.<anonymous> (src/procs/items-axios.test.ts:54:39)

Test Suites: 1 failed, 1 passed, 2 total
Tests:       2 failed, 6 passed, 8 total
Snapshots:   0 total
Time:        1.568s, estimated 2s
Ran all test suites.
```

**Comment by kettanaito** [comment]
Hey, @andreawyss. Thanks for reporting this.

I've run `npm test` in your repository and got all the tests passing:

```
 PASS  src/procs/items-fetch.test.ts
 PASS  src/procs/items-axios.test.ts

Test Suites: 2 passed, 2 total
Tests:       8 passed, 8 total
Snapshots:   0 total
Time:        2.032s
Ran all test suites.
```

- `msw: 0.19.5`
- `node: v10.x / v12.18.0`
- `node-request-interceptor@0.2.6`

Could you please mention your versions?

```bash
$ npm ls msw
$ npm ls node-request-interceptor
```

**Comment by andreawyss** [comment]
Sorry, false alarm. Just a local problem with my machine.
