### ISSUE TITLE
Error: Cannot find module 'chalk'

### ISSUE THREAD

**Issue by redraushan** [mswjs/msw#30]
# What

When we hit `msw init public` inside project, throws the following error:
```
Error: Cannot find module 'chalk'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:582:15)
    at Function.Module._load (internal/modules/cjs/loader.js:508:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/raushan/.nvm/versions/node/v10.15.3/lib/node_modules/msw/cli/init.js:3:15)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)

```

# Why

`chalk` is not available inside global `node_modules` directory.

<img width="332" alt="Screenshot 2019-09-13 at 12 51 21 AM" src="https://user-images.githubusercontent.com/12084473/64820151-dc6bcc00-d5c0-11e9-9fbd-a66d80f72585.png">

**Comment by redraushan** [comment]
@kettanaito any idea why chalk is not getting resolved when we add `msw` as global dependancy?
Everything is working fine if `msw` added locally in the project and running from local .bin directory.

This looks strange to me.

**Comment by kettanaito** [comment]
Thanks for reporting this, @redraushan.
I think the issue is that `chalk` is listed in the project's `devDependencies` instead of `dependencies`. So when `msw` is installed on your machine it never installs `chalk`, yet the `msw init` command requires chalk during its operation.

Would you mind issuing such a pull request that moves `chalk` from dev -> save dependencies?
