### ISSUE TITLE
msw worker in browser breaks puppeteer request interception

### ISSUE THREAD

**Issue by jackgeek** [mswjs/msw#418]
The problem is that starting MSW in the browser seems to break request interception due to the 
execution context being destroyed.

## Environment

- `msw: 0.21.2`
- `nodejs: v12.3.1`
- `npm: 6.14.8`
- Puppeteer version: 5.3.1

> Please also provide your browser version.
  
  Chrome: Version 85.0.4183.121 (Official Build) (64-bit)

## To Reproduce
1. Configure an environment with jest-puppeteer and MSW
2. Setup MSW (browser) in the application 
3. Ensure the msw worker is assigned to window.MSW after it is setup.
4. Create a test suite with the code below

```javascript
const METADATA = {};
beforeEach(async () => {
  await page.setDefaultNavigationTimeout(0);
  await page.setRequestInterception(true);
  page.once('request', (interceptedRequest) => {
    interceptedRequest.continue({
      method: 'POST',
      postData: JSON.stringify(METADATA),
      headers: {
        ...interceptedRequest.headers(),
        'Content-Type': 'application/json'
      }
    });
  });
  await page.goto('http://localhost:3400/puppeteerTest.json');
  await page.setRequestInterception(false);
  await page.goto('http://localhost:3400');
  await page.waitForSelector('div[name="PageBuilder"]');
  await page.evaluate(function callStart() {
    const worker = window.MSW;
    return worker.start();
  });
}, 60000);
afterEach(async () => {
  await page.evaluate(function callStart() {
    const worker = window.MSW;
    return worker.stop();
  });
});
}, 60000);
test('first test passes', async () => {
  void 0;
}, 60000);
test('second test fails', async () => {
  void 0;
}, 60000);
```
## Expected behavior
Both tests should pass

## What happens instead?
The second test will fail during the beforeEach with the following error:

(node:2136) UnhandledPromiseRejectionWarning: Error: Caught error after test environment was torn down

Execution context was destroyed, most likely because of a navigation.
    at rewriteError (C:\git\fenergo-ui-page-framework\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:261:23)
    at processTicksAndRejections (internal/process/task_queues.js:89:5)
    at ExecutionContext._evaluateInternal (C:\git\fenergo-ui-page-framework\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:215:61)
    at ExecutionContext.evaluate (C:\git\fenergo-ui-page-framework\node_modules\puppeteer\lib\cjs\puppeteer\common\ExecutionContext.js:106:16)
(node:2136) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2136) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Subsequent error is "Request Interception is not enabled!" at the point of interceptRequest.continue in the above code

**Comment by kettanaito** [comment]
Hey, @jackgeek. Thanks for reporting this. Could you please answer a few question to clarify the issue?

## Questions

1. What is your intention in combining Puppeteer's request interception and MSW? Have you consider choosing one of them, or does it go against the expected behavior?
1. Can you include your request handlers (how you configure the `worker`, its `setupWorker` call)?

The error itself (`Execution context was destroyed, most likely because of a navigation.`) means that you attempt to do something in Puppeteer in the context that no longer exist (i.e. tab was closed, or navigation to another URL has occurred). 

## Suggestions

1. Debug at which point does the execution break in your `beforeEach` hook.
1. Where is the `page` declared? Pay attention so that different tests won't attempt to access a shared `page` instance, that would cause the error above.
1. Consider removing MSW from this test setup. Is the issue fixed then?

**Comment by jackgeek** [comment]
Hi kettanaito,  Thanks for looking into this issue.

1) We are using MSW in our jest/jsdom tests and already have written mocks for our backend.  The intention is to re-use them in our jest/puppeteer environment which runs in a browser.  If we were to use Puppeteer's api to mock the backend would have to implement our mocks twice.
2) Here is one of our handlers.  I have isolated the handlers to just this one and the problem occurs, it occurs with other handlers also so I don't think it is related to the handlers, but who knows maybe it is 😮.
````typescript
import { rest } from 'msw';
import getConfig from 'src/fenergo.config.shim';
import lookups from 'fakeBackend/statics/lookups/index';

const lookupEndpointUrl = getConfig('endpointMethods.lookups.url');

type LookupsRequest = {
  keys: string[];
};

type LookupsResponse = {
  data?: LookupData;
};

type LookupData = {
  [key: string]: LookupOption[];
};

type LookupOption = {
  value: string;
  label: string;
  isActive: boolean;
};
const allLookups: LookupData = lookups;

export default rest.post<LookupsRequest, LookupsResponse>(lookupEndpointUrl, (req, res, ctx) => {
  const data: LookupData = {};

  let missingLookup = false;
  const body = req.body;

  const { keys = [] } = body;
  for (const lookupName of keys) {
    if (allLookups[lookupName]) {
      data[lookupName] = allLookups[lookupName];
    } else {
      missingLookup = true;
      console.warn(
        `Requested lookup "${lookupName}" does not exist in fakeBackend/statics/lookups`
      );
    }
  }

  if (missingLookup) {
    // faithfully reproducing what our back-end does in this situation
    return res(ctx.status(200));
  }
  return res(
    ctx.status(200),
    ctx.json({
      data,
      messages: []
    })
  );
});
```
Regarding your suggestions:
1) I have tried debugging here but it I have been unable to determine the cause of the bug.
2) `page` is a global created by the jest-puppeteer plugin we are using.  
3) The actual content of the tests in this test suite relies on the mocks but to show that it is not anything related to my code I have removed all the test bodies.  Really the gist of it is that I have MSW setup in the browser and I also have used request interception from puppeteer.

**Comment by kettanaito** [comment]
Thank you for providing more details on this issue. 

Can you double check these lines:

```js
  await page.goto('http://localhost:3400/puppeteerTest.json');
  await page.setRequestInterception(false);
  await page.goto('http://localhost:3400');
```

I have a suspicion that your intention is to _request_ `puppeteerTest.json`, not _navigate_ to it. 

Unfortunately there isn't much I can do without a reproduction repository. Could you please prepare one?

**Comment by kettanaito** [comment]
I'm closing this due to inactivity. Please see the pieces of advice above, there's a chance they will help you. If not, feel free to provide additional details or submit a reproduction repository. Without that we can't look into the issue. Thanks for understanding.
