### ISSUE TITLE
unable to verify the first certificate while intercepting the request on tests

### ISSUE THREAD

**Issue by slim-hmidi** [mswjs/msw#460]
## Environment

| Name | Version |
| ---- | ------- |
| msw  |   0.21.3 |
| node | 12.8.4 |
| OS   | windwos 10|

## Request handlers

```ts
import {setupServer} from 'msw/node';
const handlers= [
  rest.post(
    'http://localhost:8080/references/check_unique',
    (req, res) => {
      const {reference, version} = req.params;
      const fakeDataApi= {
        reference: 'x3350',
        version: 'V_1.0.0',
      };
      const isUnique = fakeDataApi.reference=== reference&& fakeDataApi.version === version;
      return res((res) => {
        res.status = 200;
        res.body = isUnique;
        return res;
      });
    },
  ),
];
export const server = setupServer(...handlers);
```

## Actual request

```js
fetch('http://localhost:8080/references/check_unique?reference=x231&version=v_1.5_3').then((res) => res.json())
```

## Current behavior

```
console.error
    Error: Error: unable to verify the first certificate
        at Object.dispatchError (C:\Users\xxx\Desktop\myProject\node_modules\jsdom\lib\jsdom\living\xhr\xhr-utils.js:62:19)
        at Request.<anonymous> (C:\Users\xxx\Desktop\myProject\node_modules\jsdom\lib\jsdom\living\xhr\XMLHttpRequest-impl.js:654:18)
        at Request.emit (events.js:327:22)
        at Request.onRequestError (C:\Users\xxx\Desktop\myProject\node_modules\request\request.js:877:8)
        at ClientRequestOverride.emit (events.js:315:20)
        at ClientRequest.<anonymous> (C:\Users\xxx\Desktop\myProject\node_modules\node-request-interceptor\src\interceptors\ClientRequest\ClientRequestOverride.ts:292:14)
        at ClientRequest.emit (events.js:315:20)
        at TLSSocket.socketErrorListener (_http_client.js:426:9)
        at TLSSocket.emit (events.js:315:20)
        at emitErrorNT (internal/streams/destroy.js:92:8) undefined

      at CustomConsole.console.error (node_modules/@testing-library/react/dist/act-compat.js:52:34)
      at VirtualConsole.<anonymous> (node_modules/jsdom/lib/jsdom/virtual-console.js:29:45)
      at Object.dispatchError (node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:65:53)
      at Request.<anonymous> (node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:654:18)
      at Request.onRequestError (node_modules/request/request.js:877:8)
```

## Expected behavior
It should intercept the request and returns correctly the message.

**Comment by slim-hmidi** [comment]
msw works well, the error thrown due to a call to external OAuth2 api to get headers when executing the api.
