### ISSUE TITLE
Integration tests failure: Too long with no output

### ISSUE THREAD

**Issue by kettanaito** [mswjs/msw#59]
## Current behavior

When run, integration tests sometimes result into a timeout on CircleCI.

- [CircleCI job](https://circleci.com/gh/open-draft/msw/137)

## Expected behavior

Integration tests are run without timeouts and exceptions, and report the status of tests appropriately. 

## Details

I've also encountered a different exception during the CI run of integration tests, when the tests would run, but random test suites would throw an exception.

```
console.info node_modules/loglevelnext/factory/PrefixFactory.js:43
      ℹ ｢atl｣: Using typescript@3.8.3 from typescript
    console.info node_modules/loglevelnext/factory/PrefixFactory.js:43
      ℹ ｢atl｣: Using tsconfig.json from /root/root/test/tsconfig.json
    console.info node_modules/loglevelnext/factory/PrefixFactory.js:43
      ℹ ｢atl｣: Checking started in a separate process...
    console.info node_modules/loglevelnext/factory/PrefixFactory.js:43
      ℹ ｢atl｣: Time: 7042ms
    console.error node_modules/jest-jasmine2/build/jasmine/Env.js:248
      Unhandled error
    console.error node_modules/jest-jasmine2/build/jasmine/Env.js:249
      Error [ERR_UNHANDLED_ERROR]: Unhandled error. (Error: Page crashed!
          at Page._onTargetCrashed (/root/root/node_modules/puppeteer/lib/Page.js:213:24)
          at CDPSession.<anonymous> (/root/root/node_modules/puppeteer/lib/Page.js:122:56)
          at CDPSession.emit (events.js:196:13)
          at CDPSession._onMessage (/root/root/node_modules/puppeteer/lib/Connection.js:200:12)
          at Connection._onMessage (/root/root/node_modules/puppeteer/lib/Connection.js:112:17)
          at WebSocket.<anonymous> (/root/root/node_modules/puppeteer/lib/WebSocketTransport.js:44:24)
          at WebSocket.onMessage (/root/root/node_modules/ws/lib/event-target.js:120:16)
          at WebSocket.emit (events.js:196:13)
          at Receiver.receiverOnMessage (/root/root/node_modules/ws/lib/websocket.js:789:20)
          at Receiver.emit (events.js:196:13)
          at Receiver.dataMessage (/root/root/node_modules/ws/lib/receiver.js:422:14)
          at Receiver.getData (/root/root/node_modules/ws/lib/receiver.js:352:17)
          at Receiver.startLoop (/root/root/node_modules/ws/lib/receiver.js:138:22)
          at Receiver._write (/root/root/node_modules/ws/lib/receiver.js:74:10)
          at doWrite (_stream_writable.js:417:12)
          at writeOrBuffer (_stream_writable.js:401:5)
          at Receiver.Writable.write (_stream_writable.js:301:11)
          at Socket.socketOnData (/root/root/node_modules/ws/lib/websocket.js:864:35)
          at Socket.emit (events.js:196:13)
          at addChunk (_stream_readable.js:290:12)
          at readableAddChunk (_stream_readable.js:271:11)
          at Socket.Readable.push (_stream_readable.js:226:10)
          at TCP.onStreamRead (internal/stream_base_commons.js:166:17))
          at Page.emit (events.js:185:17)
          at Page._onTargetCrashed (/root/root/node_modules/puppeteer/lib/Page.js:213:10)
          at CDPSession.<anonymous> (/root/root/node_modules/puppeteer/lib/Page.js:122:56)
          at CDPSession.emit (events.js:196:13)
          at CDPSession._onMessage (/root/root/node_modules/puppeteer/lib/Connection.js:200:12)
          at Connection._onMessage (/root/root/node_modules/puppeteer/lib/Connection.js:112:17)
          at WebSocket.<anonymous> (/root/root/node_modules/puppeteer/lib/WebSocketTransport.js:44:24)
          at WebSocket.onMessage (/root/root/node_modules/ws/lib/event-target.js:120:16)
          at WebSocket.emit (events.js:196:13)
          at Receiver.receiverOnMessage (/root/root/node_modules/ws/lib/websocket.js:789:20)
```

Such test where the failure originates would be marked as passing. It's necessary to ensure that exception does not happen, so there are no false positive tests.

**Comment by kettanaito** [comment]
Tacking this. The solution is to run Jest with `--runInBand` flag.

**Comment by kettanaito** [comment]
Fixed by https://github.com/open-draft/msw/commit/f7bfe46a89e90614683a56a576718f5e27b02e46.
