### ISSUE TITLE
Jest - Request sometimes not intercepted

### ISSUE THREAD

**Issue by backlit-studio** [mswjs/msw#621]
## Environment

| Name | Version |
| ---- | ------- |
| msw  | 0.26.2   |
| node | 12.19.1     |
| OS   | macOS Big Sur 11.2     |

## Request handlers

```js
import '@testing-library/jest-dom/extend-expect';
import { render, screen, waitFor } from '@testing-library/react';
import { rest } from 'msw';
import { setupServer } from 'msw/node';
import React from 'react';
import { Provider } from 'react-redux';
import { MemoryRouter, Route } from 'react-router-dom';
import configureStore from 'redux-mock-store';
import Test from '..';

const mockResponse: any = {
    // ...
};

const server = setupServer(
    rest.get(`...`, (_req, res, ctx) => {
        return res(ctx.json(mockResponse));
    }),
    )
;

describe('Test', () => {
    beforeAll(() => server.listen({ onUnhandledRequest: 'error' }));
    beforeEach(() => {
        render(<Test />, { wrapper });
    });
    afterEach(() => server.resetHandlers());
    afterAll(() => server.close());

    const mockStore = configureStore([]);
    const store = mockStore({});

    const wrapper: React.FC = ({ children }) => (
        <MemoryRouter initialEntries={['foo/1']}>
            <Provider store={store}>
                <Route path='foo/:id'>{children}</Route>
            </Provider>
        </MemoryRouter>
    );
    
    // ...

    it('...', async () => {
        await waitFor(() => screen.getByTestId('..'));
        expect(screen.queryByTestId('...')).toBeNull();
    });
});
```

## Actual request

```js
// ../Test.tsx

// ...
useEffect(() => {
        if (params.id) {
            axios.request(axiosRequestArgs);
                .then((res) => setResponse(res.data))
                .catch(() => {
                    /*...*/
                })
                .finally(() => {/*...*/);
        }
    }, [params.id]);
// ...
```

## Current behavior
The vast majority of the time everything works perfectly. Every once in a while we get the following error in our CI builds:
```
FAIL src/.../__test__/Test.test.tsx
--
257 | ● Test › ...
258 |  
259 | Network Error
260 |  
261 | at createError (node_modules/axios/lib/core/createError.js:16:15)
262 | at XMLHttpRequest.handleError (node_modules/axios/lib/adapters/xhr.js:84:14)
263 | at XMLHttpRequest.<anonymous> (node_modules/jsdom/lib/jsdom/living/helpers/create-event-accessor.js:32:32)
264 | at innerInvokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:318:25)
265 | at invokeEventListeners (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:274:3)
266 | at XMLHttpRequestImpl._dispatch (node_modules/jsdom/lib/jsdom/living/events/EventTarget-impl.js:221:9)
267 | at fireAnEvent (node_modules/jsdom/lib/jsdom/living/helpers/events.js:18:36)
268 | at requestErrorSteps (node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:128:3)
269 | at dispatchError (node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:59:3)
270 | at Object.validCORSHeaders (node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:74:5)
271 | at receiveResponse (node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:796:19)
272 | at Request.<anonymous> (node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:657:36)
273 | at Request.onRequestResponse (node_modules/request/request.js:1059:10)
```
It seems like the request isn't actually being intercepted. This is the same stacktrace I get if I never actually call `server.listen` and its complaining about bad CORS headers. I'm wondering if there is a possibility of some race condition where the test is run before requests can be intercepted, even though `server.listen` _should_ be synchronous. Either that or I'm missing something obvious (very likely)

## Expected behavior

This error to never occur

**Comment by msutkowski** [comment]
@ramirezd42 In my experience, this only happens when the test has already ran and the request runs after. Is your test `expect`ing the result of `setData` from the API request to ensure that it's been processed?

**Comment by dave-at-season** [comment]
Not directly, but I am awaiting a `waitFor` that makes sure a certain element is rendered that should only be shown after the request has completed.

Test File which has 3 tests like this:
```tsx
//... 
it('doesnt render ingredients that are not needed', async () => {
        await waitFor(() => screen.getByTestId('test-id'));
        // ... assertions
});
// ... 
```
Component File:

```tsx
// ...

const Test: React.FC<Record<string, never>> = () => {
    const params: { id?: string } = useParams();
    const reduxDispatch = useDispatch();
    const [response, setResponse] = useState<any>();
    const [loading, setLoading] = useState(false);

    useEffect(() => {
        if (params.id) {
            axios.request(axiosRequestArgs);
                .then((res) => setResponse(res.data))
                .catch(() => {
                    reduxDispatch(
                        launchAlert({
                            alertType: 'error',
                            alertMessage: `...`,
                        })
                    );
                })
                .finally(() => setLoading(false));
        }
    }, [params.id]);

    if (loading) {
        return <LoadingScreen />;
    }

    if (!response) {
        return null;
    }

    return (
                <div>
                    <h2 className={s.dateRange} data-testid="test-id">
                        ...
                    </h2>
                    { /* ... */ }
                </div>
    );
};

export default ShoppingListPrint;

```

**Comment by alettieri** [comment]
I ran into a similar issue, my issue with version `0.27.0`. Happy to file a separate issue for that if it's helpful. But I'm finding that none of the requests get intercepted. 

I also overrode the `global.fetch` function in a setup file and found that the override gets called. 

```js
beforeAll(() => {
    global.fetch = (...args) => {
        console.log('calling fetch', args)
    }
})
```

While debugging the code, I found that the interceptor handler never actually gets called: https://github.com/mswjs/msw/blob/ec64cdd7cc01e699180fce090723ab2f3006de70/src/node/createSetupServer.ts#L73

**Comment by alettieri** [comment]
To add, the only output I see when I run `DEBUG=RequestInterceptor npm run test` is:
```
  RequestInterceptor created new RequestInterceptor { interceptors: [ [Function], [Function] ] } +0ms
  RequestInterceptor use (request) => __awaiter(this, void 0, void 0, function* () {
                    const requestId = uuidv4();
                    const requestHeaders = new Headers$2(flattenHeadersObject$1(request.headers || {}));
                    if (request.headers) {
                        request.headers['x-msw-request-id'] = requestId;
                    }
                    const requestCookieString = requestHeaders.get('cookie');
                    const mockedRequest = {
                        id: requestId,
                        url: request.url,
                        method: request.method,
                        // Parse the request's body based on the "Content-Type" header.
                        body: parseBody(request.body, requestHeaders),
                        headers: requestHeaders,
                        cookies: {},
                        redirect: 'manual',
                        referrer: '',
                        keepalive: false,
                        cache: 'default',
                        mode: 'cors',
                        referrerPolicy: 'no-referrer',
                        integrity: '',
                        destination: 'document',
                        bodyUsed: false,
                        credentials: 'same-origin',
                    };
                    // Attach all the cookies stored in the virtual cookie store.
                    setRequestCookies(mockedRequest);
                    if (requestCookieString) {
                        // Set mocked request cookies from the `cookie` header of the original request.
                        // No need to take `credentials` into account, because in NodeJS requests are intercepted
                        // _after_ they happen. Request issuer should have already taken care of sending relevant cookies.
                        // Unlike browser, where interception is on the worker level, _before_ the request happens.
                        mockedRequest.cookies = parse_1(requestCookieString);
                    }
                    emitter.emit('request:start', mockedRequest);
                    if (mockedRequest.headers.get('x-msw-bypass')) {
                        emitter.emit('request:end', mockedRequest);
                        return;
                    }
                    const { response, handler } = yield getResponse(mockedRequest, currentHandlers);
                    if (!handler) {
                        emitter.emit('request:unhandled', mockedRequest);
                    }
                    if (!response) {
                        emitter.emit('request:end', mockedRequest);
                        onUnhandledRequest(mockedRequest, currentHandlers, resolvedOptions.onUnhandledRequest);
                        return;
                    }
                    emitter.emit('request:match', mockedRequest);
                    return new Promise((resolve) => {
                        var _a;
                        const mockedResponse = {
                            status: response.status,
                            statusText: response.statusText,
                            headers: response.headers.getAllHeaders(),
                            body: response.body,
                        };
                        // Store all the received response cookies in the virtual cookie store.
                        readResponseCookies(mockedRequest, response);
                        // the node build will use the timers module to ensure @sinon/fake-timers or jest fake timers
                        // don't affect this timeout.
                        timers.setTimeout(() => {
                            resolve(mockedResponse);
                        }, (_a = response.delay) !== null && _a !== void 0 ? _a : 0);
                        emitter.emit('request:end', mockedRequest);
                    });
                }) +264ms
                ```

**Comment by kettanaito** [comment]
Could somebody please create a reproduction repository?

**Comment by alettieri** [comment]
I'll work on a solution, [here](https://repl.it/@alettieri/test-msw) and [here](https://github.com/alettieri/test-msw)

**Comment by kettanaito** [comment]
Thank you for volunteering, @alettieri. Please, have you identified the issue? Let's discuss it a little so we are aligned as to what's the best way to fix it (the most obvious way isn't always the right way).

**Comment by kettanaito** [comment]
I don't think there's anything wrong with the library. We've got plenty of tests similar to yours in [the examples](https://github.com/mswjs/examples/tree/master/examples) and haven't experienced the same issue. I'd be happy to reopen this issue if somebody provides us with a reliable reproduction repository. 

 ## What should I do then to fix it?

- Ensure the same request is made in case the interception doesn't happen. Investigate what may make that unhandled request different from those scenarios when mocking works as expected. 
- Ensure any async logic and UI dependent on that async logic is properly awaited in your tests. 
- Ensure your test setup is [according to the docs](https://mswjs.io/docs/getting-started/integrate/node).
- Refer to [the examples](https://github.com/mswjs/examples/tree/master/examples), each of them features at least one integration test in Node.js.

**Comment by alettieri** [comment]
I was going to follow up on this. I actually agree, at least in my instance I think it's a race condition issue with the way the unit test is setup, not the library. Using the `DEBUG` flag was pretty helpful in allowing me to troubleshoot.

**Comment by dave-at-season** [comment]
Thanks @alettieri that helped me track down my issue as well. Turns out a test in a completely different file was mounting outside of a beforeEach which was causing these strange issues somehow
