### ISSUE TITLE
Always getting ECONNREFUSED 127.0.0.1:80 on CRA

### ISSUE THREAD

**Issue by belfortmaycon** [mswjs/msw#665]
## Environment

| Name | Version |
| ---- | ------- |
| msw  | 0.28.0   |
| node | v14.15.3     |
| OS   | macOS 10.15.7     |

## Request handlers

```js
// Example of declaration. Provide your code here.
import { setupServer } from 'msw/node'
import { rest } from 'msw'

const server = setupServer(
  rest.get('http://localhost/v1/test/hierarchy', (req, res, ctx) => {
    const query = req.url.searchParams
    const id = query.get("id")

    res(
      ctx.status(200),
      ctx.json({}),
    );
  }),
)
rest.get('/v1/test/hierarchy', (req, res, ctx) => {
    const query = req.url.searchParams
    const id = query.get("id")

    res(
      ctx.status(200),
      ctx.json({}),
    );
  }),
)
)

beforeAll(() => {
  server.listen({
    onUnhandledRequest: 'error',
  });
  server.printHandlers(); // optional, but helpful!
  console.log(`msw server started!`);
});

afterEach(() => server.resetHandlers());

afterAll(() => server.close());
```

## Actual request

it('test', async () => {
    const resp = await fetch('http://localhost/v1/test/hierarchy?id=1');
     //const resp = await fetch('/v1/test/hierarchy');

    // expect(resp).toEqual(1);
  })
```js
// Example of making a request. Provide your code here.
fetch('???').then((res) => res.json())
```

## Current behavior

I'm not sure if msw works with CRA projects. It's always returning 
```
console.error
      [MSW] Error: captured a request without a matching request handler:
      
        • GET http://localhost/v1/test/hierarchy
      
      If you still wish to intercept this unhandled request, please create a request handler for it.
      Read more: https://mswjs.io/docs/getting-started/mocks

      at consoleObject.<computed> [as error] (node_modules/filter-console/index.js:46:4)
      at onUnhandledRequest (node_modules/msw/node/lib/index.js:7120:21)
      at node_modules/msw/node/lib/index.js:7620:25
      at fulfilled (node_modules/msw/node/lib/index.js:50:58)

    console.error
      Error: Error: connect ECONNREFUSED 127.0.0.1:80
          at Object.dispatchError (/Users/Developer/git/pcm-ui/node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:62:19)
          at Request.<anonymous> (/Users/Developer/git/pcm-ui/node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:655:18)
          at Request.emit (events.js:327:22)
          at Request.onRequestError (/Users/Developer/git/pcm-ui/node_modules/request/request.js:877:8)
          at ClientRequestOverride.emit (events.js:315:20)
          at ClientRequest.<anonymous> (/Users/Developer/git/pcm-ui/node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/createClientRequestOverride.ts:329:14)
          at ClientRequest.emit (events.js:315:20)
          at Socket.socketErrorListener (_http_client.js:469:9)
          at Socket.emit (events.js:315:20)
          at emitErrorNT (internal/streams/destroy.js:106:8) undefined

      at consoleObject.<computed> [as error] (node_modules/filter-console/index.js:46:4)
      at VirtualConsole.<anonymous> (node_modules/jsdom/lib/jsdom/virtual-console.js:29:45)
      at Object.dispatchError (node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:65:53)
      at Request.<anonymous> (node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:655:18)
      at Request.onRequestError (node_modules/request/request.js:877:8)

  ● test api call › test

    TypeError: Network request failed

      at node_modules/whatwg-fetch/dist/fetch.umd.js:535:18
      at Timeout.task [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:514:19)
```
## Expected behavior

Can mock the request

**Comment by kettanaito** [comment]
Hey, @belfortmaycon. 

There are two issues with the code you've shared above. First, you are not _returning_ a mocked response in your resolver:

```diff
const server = setupServer(
  rest.get('http://localhost/v1/test/hierarchy', (req, res, ctx) => {
    const query = req.url.searchParams
    const id = query.get("id")

-   res(
+   return res(
      ctx.status(200),
      ctx.json({}),
    );
  }),
)
```

Without returning a mocked response that handler doesn't affect the request in any way, allowing it to fall through. That's the behavior you're experiencing, as your test makes the actual request to a non-existing `http://localhost/v1/test/hierarchy` that fails to connect to the `127.0.0.1:80` (`localhost`) host respectively. Returning the `res()` function call, as shown above, will fix the issue. 

The second one is that your other `rest.get` handler is _outside_ of the `setupServer` call:

```js
const server = setupServer(
  rest.get('http://localhost/v1/test/hierarchy', (req, res, ctx) => {
    const query = req.url.searchParams
    const id = query.get("id")

    res(
      ctx.status(200),
      ctx.json({}),
    );
  }),
) // the end of the "setupServer()" function call.
// Everything below is not passed anywhere.
rest.get('/v1/test/hierarchy', (req, res, ctx) => {
    const query = req.url.searchParams
    const id = query.get("id")

    res(
      ctx.status(200),
      ctx.json({}),
    );
  }),
)
)
```

I think that's an issue of pasting the code, but double-check that you're passing all the handlers you want to the `setupServer` to take effect. 

Please let me know if my suggestion helps.

**Comment by belfortmaycon** [comment]
Thanks @kettanaito work all!
