### ISSUE TITLE
Failure when running in CI (TypeError: The "options.agent" property must be one of Agent-like Object, undefined, or false)

### ISSUE THREAD

**Issue by romansndlr** [mswjs/msw#750]
## Describe the bug
After upgrading to 0.28.0 have been getting these errors only in CI while running tests:

```
  TypeError: The "options.agent" property must be one of Agent-like Object, undefined, or false. Received an instance of ObjectTypeError [ERR_INVALID_ARG_TYPE]: The "options.agent" property must be one of Agent-like Object, undefined, or false. Received an instance of Object

      at Object.proxiedOriginalRequest (node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/index.ts:72:29)
      at ClientRequestOverride.<anonymous> (node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/createClientRequestOverride.ts:296:19)
      at step (node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/createClientRequestOverride.js:33:23)
      at Object.next (node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/createClientRequestOverride.js:14:53)
      at fulfilled (node_modules/@mswjs/interceptors/lib/interceptors/ClientRequest/createClientRequestOverride.js:5:58)
```

## Environment

- `msw: 0.28.0`
- `nodejs: 12.0.0`
- `npm: 6.14.11`

**Comment by kettanaito** [comment]
Hey. Could you please create a reproduction repository for this issue?

The surface of Node.js request is gigantic. If you want to get this resolved, always provide a reproduction repo. Thank you.

**Comment by zachtaylor21** [comment]
@romansndlr I also just ran into this error when testing locally. Turns out I had some requests going out that I forgot to write request handlers for. Adding the request handlers fixed the issue for me.

**Comment by kettanaito** [comment]
I was able to reproduce this upgrading to `jest@27`. This appears to be a compatibility issue with the latest version of jest. The issue is opened in https://github.com/mswjs/interceptors/issues/126.

**Comment by jonkoops** [comment]
@kettanaito could we get a release of `msw` with a bumped version of `@mswjs/interceptors` to resolve this issue?

**Comment by kettanaito** [comment]
@jonkoops, sure. I'll make a release in the upcoming day or two. Thank you for your patience.
