### ISSUE TITLE
MSW does not intercept POST request

### ISSUE THREAD

**Issue by hhimanshu** [mswjs/msw#777]
Hello there,

Here is a working demo on codesandbox

https://codesandbox.io/s/msw-post-test-fail-e39dc

It contains a test, which fails for `POST` method.

## Environment

| Name | Version |
| ---- | ------- |
| msw  | 0.29.0   |
| node | XXX     |
| OS   | XXX     |

## Request handlers

```ts
rest.post("*/workspaces", (req, res, context) => {
    res(context.status(201), context.json({ status: 200 }));
  })
```

## Actual request

```ts
const response = await fetch(`/workspaces`, {
      method: "POST",
      body: JSON.stringify({
        name: "A Test Name"
      })
    });
```

## Current behavior
In codesandbox, I see
```
Expected: 201
Received: 405
```

However, in my other project with same `msw` dependency, I see the following stacktrace
```

    console.warn
      [MSW] Expected a mocking resolver function to return a mocked response Object, but got: undefined. Original response is going to be used instead.

      at next (node_modules/msw/node/lib/index.js:7639:21)
      at fulfilled (node_modules/msw/node/lib/index.js:50:58)

    console.warn
      [MSW] Expected a mocking resolver function to return a mocked response Object, but got: undefined. Original response is going to be used instead.

      at next (node_modules/msw/node/lib/index.js:7639:21)
      at fulfilled (node_modules/msw/node/lib/index.js:50:58)

    console.error
      Error: Error: connect ECONNREFUSED 127.0.0.1:80
          at Object.dispatchError (/Users/hhimanshu/code/prj/node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:62:19)
          at Request.<anonymous> (/Users/hhimanshu/code/prj/node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:654:18)
          at Request.emit (node:events:377:35)
          at Request.onRequestError (/Users/hhimanshu/code/prj/node_modules/request/request.js:877:8)
          at ClientRequestOverride.emit (node:events:365:28)
          at ClientRequest.<anonymous> (/Users/hhimanshu/code/prj/node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/createClientRequestOverride.ts:322:14)
          at ClientRequest.emit (node:events:365:28)
          at Socket.socketErrorListener (node:_http_client:447:9)
          at Socket.emit (node:events:365:28)
          at emitErrorNT (node:internal/streams/destroy:193:8) undefined

      at VirtualConsole.<anonymous> (node_modules/jsdom/lib/jsdom/virtual-console.js:29:45)
      at Object.dispatchError (node_modules/jsdom/lib/jsdom/living/xhr/xhr-utils.js:65:53)
      at Request.<anonymous> (node_modules/jsdom/lib/jsdom/living/xhr/XMLHttpRequest-impl.js:654:18)
      at Request.onRequestError (node_modules/request/request.js:877:8)
      at ClientRequest.<anonymous> (node_modules/@mswjs/interceptors/src/interceptors/ClientRequest/createClientRequestOverride.ts:322:14)

  ● Mock › POST /workspaces

    TypeError: Network request failed

      at node_modules/react-app-polyfill/node_modules/whatwg-fetch/dist/fetch.umd.js:541:18
      at Timeout.task [as _onTimeout] (node_modules/jsdom/lib/jsdom/browser/Window.js:391:19)

```

## Expected behavior

I expected the `POST` requests to be intercepted correctly in node based environment. (P.S I have not tested on browser environment yet)

**Comment by hhimanshu** [comment]
I take my issue back. I am so stupid, I was missing `return` keyword

Instead of 
```ts
rest.post("*/workspaces", (req, res, context) => {
    res(context.status(201), context.json({ status: 200 }));
  }),
```

I needed

```ts
rest.post("*/workspaces", (req, res, context) => {
       return res(context.status(201), context.json({ status: 200 }));
  }), // ^^^
```
