### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"

### ISSUE THREAD

**Issue by adesurirey** [mswjs/msw#865]
## Environment

| Name | Version |
| ---- | ------- |
| msw  | 0.26.0   |
| node | 12.18.1     |
| OS   | macOS 11.4     |

## Request handlers

```js
import { setupServer } from 'msw/node'
import { rest } from 'msw'

export const server = setupServer(
  rest.get("https://app.sandbox.buyco.co/api/users", (_req, res, ctx) => {
    return res(ctx.json({ data: [] }));
  }),
)

beforeAll(() => {
  server.listen({
    onUnhandledRequest: "warn",
  });
});

afterEach(() => {
  server.resetHandlers();
});

afterAll(() => {
  server.close();
});

```

## Actual request

```js
import superagent from "superagent";

superagent.get("https://app.sandbox.buyco.co/api/users")
```

## Current behavior

When testing, the request isn't catch and I have two things in console: 

1. This Node error 
```
(node:30378) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_PROTOCOL]: Protocol "http:" not supported. Expected "https:"
    at new ClientRequest (_http_client.js:152:11)
    at request (https.js:314:10)
    at Object.proxiedOriginalRequest (/Users/arnaud/code/buyco/buyco-client-app/node_modules/node-request-interceptor/src/interceptors/ClientRequest/index.ts:73:29)
    at ClientRequestOverride.<anonymous> (/Users/arnaud/code/buyco/buyco-client-app/node_modules/node-request-interceptor/src/interceptors/ClientRequest/ClientRequestOverride.ts:282:15)
    at step (/Users/arnaud/code/buyco/buyco-client-app/node_modules/node-request-interceptor/lib/interceptors/ClientRequest/ClientRequestOverride.js:33:23)
    at Object.next (/Users/arnaud/code/buyco/buyco-client-app/node_modules/node-request-interceptor/lib/interceptors/ClientRequest/ClientRequestOverride.js:14:53)
    at fulfilled (/Users/arnaud/code/buyco/buyco-client-app/node_modules/node-request-interceptor/lib/interceptors/ClientRequest/ClientRequestOverride.js:5:58)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(node:30378) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 58)
```

2. A msw warning about the same request but done via `http` and unhandled 

```
[MSW] Warning: captured a GET http://app.sandbox.buyco.co/api/users request without a corresponding request handler.
    
      If you wish to intercept this request, consider creating a request handler for it:
    
      rest.get('http://app.sandbox.buyco.co/api/users', (req, res, ctx) => {
        return res(ctx.text('body'))
      })

      at onUnhandledRequest (../../node_modules/msw/node/index.js:2816:21)
      at Object.<anonymous> (../../node_modules/msw/node/index.js:2911:25)
      at fulfilled (../../node_modules/msw/node/index.js:38:58)
```

Even if I update the handler to use `http` as suggested by the warning, result is the same. 

## Expected behavior

It should catch my superagent request in test environment (Node).

Note that the same handler works perfectly in the browser. 

## Screenshots

![image](https://user-images.githubusercontent.com/22000544/129588985-db2dee93-9c63-4bb0-bd30-7fe8c8db7e7d.png)

**Comment by kettanaito** [comment]
Hey, @adesurirey. 

Please always search for existing issues before opening a new one. There are multiple similar issues solved in the past and even one identical to yours:

- **Identical issue:** #632
- #486
- #327
- #263

## Solution

**Update the version of `msw` you're using**. `0.26.0` is an extremely old version. You can check the latest published version on [npm](https://www.npmjs.com/package/msw) or by running `npm view msw` in your project.

As a rule of thumb, always update to the latest version before submitting an issue.
Thanks.

**Comment by adesurirey** [comment]
Hey @kettanaito, I'm very sorry about that... thank you for the solution.

**Comment by kettanaito** [comment]
Don't be, I'm glad that the issue will be resolved once you update.
